### ISSUE TITLE
Not enough Porn.

### ISSUE THREAD

**Issue by woofwoof4723** [JimmieThomson/Mods_SPT-AKI#1]
blah blah blah porn porn!! YES YES YES porn!

https://cdn.discordapp.com/attachments/465884347686191115/1239903035115704380/SPOILER_v95kfvdom5rc1.png?ex=66449d2f&is=66434baf&hm=3b303eb049ada6223a3e290c648cc87c6951542543080c0032cdb5645e8cdc27&

**Comment by JimmieThomson** [comment]
don't
